unity_catalog:
  catalog_name: workspace
  schema_name: default

tables:
  training_data: "synthetic_propensity_model_training_data"
  scoring_data: "synthetic_propensity_model_scoring_data"
  processed_training_data: "final_xgboost_input_matrix_training"
  processed_scoring_data: "final_xgboost_input_matrix_scoring"

ml_settings:
  target_column: "Purchased Next 30D"
  model_registry_name: "workspace.default.purchase_propensity_xgb"
